### ISSUE TITLE
Good Library but doesn't seem to work with obx and getx

### ISSUE THREAD

**Issue by syleishere** [aagarwal1012/Animated-Text-Kit#249] opened 2021-05-13 06:35 UTC
```
             child: Obx(() => AnimatedTextKit(
                  animatedTexts: [
                    ColorizeAnimatedText(
                      "${c.song0.value}",
                      textStyle: colorizeTextStyle,
                      colors: colorizeColors,
                    ),
                  ],
                  isRepeatingAnimation: true,
                  onTap: () {
                    print("Tap Event");
                  },
                ),
              ),
```
Doesn't update the text at all.

**Comment by syleishere** [comment] 2021-05-13 06:37
Maybe doesn't support it not sure, not sure why wouldn't work with #3 top plugin in world getx for state management.

**Comment by SirusCodes** [comment] 2021-05-14 05:34
@syleishere I don't think there should be any issue with any of the state management solutions as all of them play by the rules of Flutter (IFAIK lemme know if GetX is different).
Maybe you can give us some logs or some specific issue with the package then we can work on it.

TBH, I have 0 experience with GetX so it would be great if you can provide us with a project to reproduce this.

**Comment by anggaaryas** [comment] 2021-05-20 08:53
Maybe related to this?

#243 
#247

**Comment by SirusCodes** [comment] 2021-05-20 14:13
Oh @aagarwal1012 have you tested this https://github.com/aagarwal1012/Animated-Text-Kit/pull/243#issuecomment-829043893??
I think this will fix it and we won't require any workaround for it🤔

**Comment by awhitford** [comment] 2021-07-05 19:15
@syleishere Try adding a `key` like this:
```dart
             child: Obx(() => AnimatedTextKit(
                  key: ValueKey(c.song0.value),
                  animatedTexts: [
                    ColorizeAnimatedText(
                      "${c.song0.value}",
                      textStyle: colorizeTextStyle,
                      colors: colorizeColors,
                    ),
                  ],
                  isRepeatingAnimation: true,
                  onTap: () {
                    print("Tap Event");
                  },
                ),
              ),
```

**Comment by aagarwal1012** [comment] 2022-06-05 14:22
Closing this comment, as the issue seems to be resolved.

**Closed by aagarwal1012** 2022-06-05 14:22 UTC
