### ISSUE TITLE
Error: 'Characters' isn't a type

### ISSUE THREAD

**Issue by Eshetiegashaw** [aagarwal1012/Animated-Text-Kit#141] opened 2020-10-28 10:00 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Flutter:**
 - version
 - channel

**Dart:**
 - version

**Additional context**

**Comment by aagarwal1012** [comment] 2020-10-28 10:28
@awhitford please check this issue.

**Comment by awhitford** [comment] 2020-10-28 12:03
> /C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/animated_text_kit-2.5.1/lib/src/colorize.dart:105:28: Error: 'Characters' isn't a type. final _textCharacters = <Characters>[]; ^^^^^^^^^^ /C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/animated_text_kit-2.5.1/lib/src/colorize.dart:118:32: Error: The getter 'characters' isn't defined for the class 'String'. Try correcting the name to the name of an existing getter, or defining a getter or field named 'characters'. _textCharacters.add(text.characters);

@Eshetiegashaw Please do a `flutter clean` and `flutter pub get` and if the problem persists, please provide `flutter doctor -v` output.

This issue is a duplicate of #140, so I'm going to close this duplicate and track the issue under #140.

**Comment by naseebbajracharya** [comment] 2020-11-19 12:29
> > /C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/animated_text_kit-2.5.1/lib/src/colorize.dart:105:28: Error: 'Characters' isn't a type. final _textCharacters = []; ^^^^^^^^^^ /C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/animated_text_kit-2.5.1/lib/src/colorize.dart:118:32: Error: The getter 'characters' isn't defined for the class 'String'. Try correcting the name to the name of an existing getter, or defining a getter or field named 'characters'. _textCharacters.add(text.characters);
> 
> @Eshetiegashaw Please do a `flutter clean` and `flutter pub get` and if the problem persists, please provide `flutter doctor -v` output.
> 
> This issue is a duplicate of #140, so I'm going to close this duplicate and track the issue under #140.

@awhitford @aagarwal1012 `flutter clean` and `flutter pub get` didn't work at all, I'm still getting Characters isn't a type error. So, here's my `flutter doctor -v` output
![flutter-dr](https://user-images.githubusercontent.com/34349150/99666347-ff322400-2a92-11eb-8030-6599399cc8cb.JPG)

**Comment by awhitford** [comment] 2020-11-19 17:17
It appears that this may be a known issue:  https://github.com/flutter/flutter/issues/59645#issuecomment-645240371
This comment suggests deleting the `.dart_tool` directory and then running `flutter run`.
Rather than delete the directory, I would simply rename the file inside, like:
```sh
$ pushd .dart_tool
$ mv package_config.json package_config.json.old
$ popd
```
And then run `flutter run`.  This should rebuild that `package_config.json` file, and I'd be curious to see the diff with `package_config.json.old`.

Alternatively, please consider upgrading to the latest Flutter **stable** version:
 * Flutter (Channel stable, 1.22.4) / Dart version 2.10.4

`flutter upgrade` should do the trick.  [Others suggested this as a fix.](https://github.com/flutter/flutter/issues/59645#issuecomment-648581824)

I will admit that I do not understand why it is failing to get the `characters` package, but our testing is done with later versions, and we know that works.

**Comment by naseebbajracharya** [comment] 2020-11-20 05:03
@awhitford yeah, it worked after upgrading Flutter to the latest version, but now it shows this warning note even if the application runs.

Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\connectivity-0.4.9+3\android\src\main\java\io\flutter\plugins\connectivity\ConnectivityBroadcastReceiver.java uses or overrides a deprecated API.
Note: Recompile with -Xlint: deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint: unchecked for details.

**Comment by SirusCodes** [comment] 2020-11-20 06:28
> @awhitford yeah, it worked after upgrading Flutter to the latest version, but now it shows this warning note even if the application runs.
> 
> Note: C:\src\flutter.pub-cache\hosted\pub.dartlang.org\connectivity-0.4.9+3\android\src\main\java\io\flutter\plugins\connectivity\ConnectivityBroadcastReceiver.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint: deprecation for details.
> Note: Some input files use unchecked or unsafe operations.
> Note: Recompile with -Xlint: unchecked for details.

This won't cause any issues, everything will work fine👍 and this is because of the connectivity package...you can upgrade that to the latest version.

**Comment by awhitford** [comment] 2020-11-20 16:49
@naseebbajracharya You should also upgrade your [connectivity](https://pub.dev/packages/connectivity/) dependency since the latest version is [2.0.2](https://pub.dev/packages/connectivity/changelog).  I'll guess that those deprecation warnings will disappear. Regardless, as @SirusCodes says, those warnings are not related to this package.

I'm glad to hear the `characters` issue has been resolved.

**Closed by awhitford** 2020-11-20 16:49 UTC
Labels: duplicate
